twbs/bootlint

Gruntfile.js, src/bootlint.js, test/bootlint_test.js, test/fixtures/jquery/and_bs_js_both_missing.html
Fixes #72.
CC: @hnrch02 for review
=> Emit different warning message when jQuery & bootstrap.js both absent

src/bootlint.js, test/bootlint_test.js, test/fixtures/navbar/navbar-left-bad.html, test/fixtures/navbar/navbar-left-right-on-navbar.html, test/fixtures/navbar/navbar-left-right-valid.html, test/fixtures/navbar/navbar-right-bad.html
=> Complain about .navbar-{left,right} outside of .navbar

src/bootlint.js, test/bootlint_test.js, test/fixtures/modal/with-hide.html
=> Complain about .modal.hide Bootstrap v2-ism

src/cli.js
Refs #212
Refs #211
/cc @cvrebert @XhmikosR
=> Use more common way to determine if stdin should be read

src/bootlint.js, test/bootlint_test.js, test/fixtures/carousel/controls.html, test/fixtures/carousel/missing-active-item.html, test/fixtures/carousel/missing-inner.html, test/fixtures/carousel/multiple-active-item.html, test/fixtures/carousel/multiple-inner.html, test/fixtures/carousel/valid.html
=> Lint structure of Carousels

package.json, src/cli.js
=> Bump commander.js and add program description to help

package.json, test-infra/npm-shrinkwrap.json
=> Update bluebird to 2.9.12

package.json, src/bootlint.js, test-infra/npm-shrinkwrap.json, test/bootlint_test.js, test/fixtures/grid/spacer-col/void-elements.html
=> Don't warn for empty spacer when element is self closing

README.md
Use HTTPS instead of HTTP where possible
=> Use HTTPS instead of HTTP where possible

README.md
Points at the new grunt-bootlint location.
=> New URL for grunt-bootlint

src/bootlint.js, test/bootlint_test.js, test/fixtures/x-ua-compatible/lowercase.html
=> Allow "x-ua-compatible: ie=edge"

.jshintrc
Relevant docs: http://jshint.com/docs/options/#futurehostile
CC: @hnrch02 for approval
=> JSHint: enable futurehostile option

package.json, test-infra/npm-shrinkwrap.json
=> Bump glob to ^5.0.3

README.md
=> Add MIT License badge to README

src/bootlint.js, test/bootlint_test.js, test/fixtures/tooltips/in-btn-groups.html
=> add backticks to W008 message for better Markdown rendering

src/bootlint.js, test/bootlint_test.js, test/fixtures/outdated/bootstrap-css.html, test/fixtures/outdated/bootstrap-js.html, test/fixtures/outdated/bootstrap-min-css.html, test/fixtures/outdated/bootstrap-min-js.html, test/fixtures/outdated/js-version-not-in-url-current.html, test/fixtures/outdated/js-version-not-in-url-outdated.html
Updates the tests which caused #288 to error out.
=> Update to v3.3.5

src/bootlint.js, test/bootlint_test.js, test/fixtures/navbar/navbar-container.html
=> Clarify W012

app.js
Fixes https://github.com/cvrebert/lmvtfy/issues/119
=> HTTP API: Set max incoming entity size

package.json, src/cli.js, test/cli_test.js
[X-Ref: #179] Begin adding tests for CLI
=> [X-Ref: #179] Begin adding tests for CLI

.travis.yml, test/fixtures/cli/x-ua-compatible-missing.output.txt
=> Add Travis test that CLI isn't a no-op

.travis.yml, package.json, src/cli-main.js, src/cli.js
=> Add cli-main.js which actually invokes cli.js's function

.travis.yml, test-infra/S3Cachefile.json
* use Jekyll v3.1.2 and remove rouge since it's a Jekyll dependency now
* use ruby 2.2
/CC @cvrebert
=> Update Travis config.

src/bootlint.js, test/bootlint_test.js, test/fixtures/form/nested-form-groups.html, test/fixtures/form/valid.html
Resolves #315
- Add E050 to check for nested form groups.
- Add new fixtures to test the new lint
- Update bootlint_test to call new fixtures
=> #315 - Add new lint for nested form groups

README.md
Fixes #346
Discuss benefits
Add how to install the bookmarklet
Add how to use the bookmarklet
=> #346 - Update in the browser readme section

src/bootlint.js, test/bootlint_test.js, test/fixtures/containers/fixed-row-same-elem.html, test/fixtures/containers/missing.html, test/fixtures/containers/row-inside-modal-body.html
=> Allow `.row` in `.modal-body`.

.travis.yml
=> Travis: remove bundle cache.

package-lock.json, package.json
This is basically a fork of rensbaardman/rewire#master which has quite a few fixes missing from upstream.
There's a bug in rewire jhnns/rewire/167 which affects Node.js 12.
=> Switch to twbs/rewire#master.
